// Copyright 2025 QMK -- generated source code only, font retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `painter-convert-font-image` with arguments:
//    format         | mono2
//    unicode_glyphs | 
//    output         | fonts
//    input          | pixellari.png

#pragma once

#include <qp.h>

extern const uint32_t font_pixellari_length;
extern const uint8_t  font_pixellari[1651];
